### ISSUE TITLE
release request for melodic

### ISSUE THREAD

**Issue by eisoku9618** [tork-a/rtshell-release#3]
@k-okada sensei,

I would like to use rtshell via apt in melodic, but it is released until kinetic and it is not released since lunar.

Could you release ros-melodic-rtshell?

**Comment by k-okada** [comment]
ok, released rtsprofile https://github.com/ros/rosdistro/pull/22099

**Comment by eisoku9618** [comment]
Thank you.
Just to confirm, do you have to release rtsprofile first in order to release rtshell since rtshell depends on rtsprofile?

**Comment by k-okada** [comment]
Release rtshell -> https://github.com/ros/rosdistro/pull/22102

**Comment by eisoku9618** [comment]
Thank you again!
